name: rh_collector
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.3
  path_provider: ^2.0.3
  intl: ^0.17.0
  get: ^4.3.8
  shared_preferences: ^2.0.8
  google_ml_vision: ^0.0.7
  image: ^3.0.8
  syncfusion_flutter_pdf: ^19.3.57-beta
  file_picker: ^4.3.0
  sembast: ^3.1.1+1
  permission_handler: ^9.0.2
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  test: ^1.17.12


flutter:
  uses-material-design: true

flutter_icons:
  ios: false
  android: true
  image_path: "assets/planner2.png"
