name: rh_collector
description: A new Flutter project.
publish_to: 'none' 
version: 1.4.7+2

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.20.2
  path_provider: ^2.1.5
  get: ^4.6.6
  shared_preferences: ^2.3.3
#  google_ml_vision: ^0.0.8
  image: ^4.3.0
  syncfusion_flutter_pdf: ^29.2.5
  file_picker: ^10.1.9
  sembast: ^3.7.2
  permission_handler: ^12.0.0+1
  csv: ^6.0.0
  awesome_notifications: ^0.10.1
  numberpicker: ^2.1.2
  flutter_slidable: ^4.0.0
  device_info_plus: ^11.1.1
  graphic: ^2.5.0
  photo_data_picker:
    git:
      url: https://github.com/lavruh/photo_data_picker.git
  file: ^7.0.1
  path: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.1


flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  ios: false
  android: true
  image_path: "assets/planner2.png"
